# Generated by Django 4.1.1 on 2022-10-12 12:02

from django.db import migrations, models
import django.db.models.deletion
import mylab.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Collectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('abbre', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('additives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.additives')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interval', models.CharField(max_length=50)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('fix_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('emp_id', models.IntegerField(default=mylab.models.Prescription.ids, editable=False, unique=True, verbose_name='Code')),
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateField(help_text='Please Enter Your Correct Date Of Birth', null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('status', models.CharField(choices=[('In Treatement', 'In Treatement'), ('Recovered', 'Recovered'), ('New Patient', 'New Patient')], max_length=20, null=True)),
                ('town', models.CharField(choices=[('Yaounde', 'Yaounde'), ('Douala', 'Douala'), ('Bamenda', 'Bamenda'), ('Buea', 'Buea'), ('Baffoussam', 'Baffoussam'), ('Ngaoundere', 'Ngaoundere'), ('Ebolowa', 'Ebolowa'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.doctor')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='Medicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('unit', models.CharField(choices=[('', '')], max_length=20)),
                ('regular_price', models.FloatField()),
                ('assured_price', models.FloatField()),
                ('collectors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.collectors')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.interval')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.technique')),
            ],
        ),
    ]
