# Generated by Django 4.0.6 on 2022-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('In Treatement', 'In Treatement'), ('Recovered', 'Recovered'), ('New Patient', 'New Patient')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='town',
            field=models.CharField(choices=[('Yaounde', 'Yaounde'), ('Douala', 'Douala'), ('Bamenda', 'Bamenda'), ('Buea', 'Buea'), ('Baffoussam', 'Baffoussam'), ('Ngaoundere', 'Ngaoundere'), ('Ebolowa', 'Ebolowa'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=50),
        ),
    ]
