# Generated by Django 4.1.1 on 2022-10-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0003_alter_results_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
