# Generated by Django 4.0.6 on 2022-08-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0004_prescription_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='clinical_info',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='consulting_service',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='physical_state',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='physiological_state',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescribed_analyses',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='private_initial',
        ),
    ]
