# Generated by Django 4.1.1 on 2022-10-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0012_alter_results_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='currency',
            field=models.CharField(choices=[('R', 'ZAR'), ('$', 'USD'), ('C', 'FCFA')], default='FCFA', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
