# Generated by Django 4.0.6 on 2022-08-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0013_alter_prescription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='uid',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.CharField(editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
