# Generated by Django 4.1.1 on 2022-10-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0013_doctor_currency_doctor_price_doctor_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='quantity',
        ),
    ]
