# Generated by Django 4.0.6 on 2022-08-12 15:52

from django.db import migrations, models
import mylab.models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0014_prescription_uid_alter_prescription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='uid',
        ),
        migrations.AddField(
            model_name='prescription',
            name='emp_id',
            field=models.IntegerField(default=mylab.models.Prescription.ids, editable=False, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
