# Generated by Django 4.0.6 on 2022-08-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0015_remove_prescription_uid_prescription_emp_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='DOB',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='prescription',
            name='dob',
            field=models.DateField(help_text='Please Enter Your Correct Date Of Birth', null=True),
        ),
    ]
