# Generated by Django 4.1.1 on 2022-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0016_rename_dob_prescription_date_added_prescription_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ('date_added',)},
        ),
        migrations.RemoveField(
            model_name='medicals',
            name='bench',
        ),
        migrations.RemoveField(
            model_name='medicals',
            name='debit',
        ),
        migrations.AlterField(
            model_name='medicals',
            name='unit',
            field=models.CharField(choices=[('', '')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
