# Generated by Django 4.1.1 on 2022-09-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0017_alter_prescription_options_remove_medicals_bench_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabTechnician',
        ),
        migrations.AddField(
            model_name='collectors',
            name='abbre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interval',
            name='fix_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interval',
            name='maximum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interval',
            name='minimum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='technique',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
