# Generated by Django 4.1.1 on 2022-10-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0018_alter_results_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
    ]
