# Generated by Django 4.0.6 on 2022-08-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(max_length=255)),
                ('paillaise_noms', models.CharField(choices=[('Syrologie', 'Syrologie'), ('HIV', 'HIV')], max_length=50)),
                ('additives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.additives')),
            ],
        ),
        migrations.CreateModel(
            name='Collectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('additives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.additives')),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interval', models.CharField(choices=[('Max', 'Maximum'), ('Min', 'Minimum')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNI', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('DOB', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
                ('telephone1', models.IntegerField()),
                ('telephone2', models.IntegerField(blank=True, null=True)),
                ('town', models.CharField(choices=[('Yde', 'Yaounde'), ('Dla', 'Douala'), ('Bda', 'Bamenda'), ('Bu', 'Buea'), ('Baf', 'Baffoussam'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=50)),
                ('physical_state', models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=50)),
                ('insurance', models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=50)),
                ('consulting_service', models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=50)),
                ('private_initial', models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=50)),
                ('prescriber', models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=50)),
                ('clinical_info', models.CharField(blank=True, max_length=50)),
                ('prescribed_analyses', models.CharField(blank=True, max_length=50)),
                ('physiological_state', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Observation', 'Observation'), ('Patience', 'Patience')], max_length=50)),
                ('abbr', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('regular_price', models.FloatField()),
                ('assured_price', models.FloatField()),
                ('bench', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.analysis')),
                ('collectors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.collectors')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicals_debit', to='mylab.analysis')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.interval')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.technique')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='collectors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.collectors'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.interval'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.measurement'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylab.technique'),
        ),
    ]
