# Generated by Django 4.0.6 on 2022-08-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0005_remove_prescription_clinical_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
