# Generated by Django 4.0.6 on 2022-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0007_alter_prescription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.CharField(default=1, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
