# Generated by Django 4.0.6 on 2022-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0012_alter_prescription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
